#!/usr/bin/env bash
set -Eeuo pipefail

# Dynamic Bubble - Pywal synchronization helper.
# This script never modifies the root-owned theme source.

THEME_NAME="Dynamic_bubble"
CACHE_DIR="/var/cache/sddm-theme"
WAL_CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/wal"
QUIET=false

if [[ "${1:-}" == "--quiet" ]]; then
    QUIET=true
fi

log() {
    $QUIET || printf '%s\n' "$*"
}

fail() {
    printf 'Dynamic Bubble: %s\n' "$*" >&2
    exit 1
}

normalize_color() {
    local value="${1:-}"
    value="${value//\"/}"
    value="${value//\'/}"
    if [[ "$value" =~ ^#[0-9A-Fa-f]{6}$ ]]; then
        printf '%s' "$value"
    elif [[ "$value" =~ ^[0-9A-Fa-f]{6}$ ]]; then
        printf '#%s' "$value"
    else
        printf '%s' "$2"
    fi
}

[[ -d "$CACHE_DIR" ]] || fail "cache directory is missing; run ./install.sh first"
[[ -w "$CACHE_DIR" ]] || fail "$CACHE_DIR is not writable by $USER"

WALLPAPER=""
if [[ -f "$WAL_CACHE/wal" ]]; then
    WALLPAPER="$(<"$WAL_CACHE/wal")"
fi
[[ -n "$WALLPAPER" && -f "$WALLPAPER" ]] || fail "Pywal wallpaper was not found in $WAL_CACHE/wal"

background="#1a1b26"
foreground="#ffffff"
color1="#f38ba8"
color3="#f9e2af"
color8="#6c7086"
color10="#a6e3a1"
color11="#8caaee"
color12="#89b4fa"

if [[ -f "$WAL_CACHE/colors.sh" ]]; then
    # colors.sh is generated by Pywal for the current user.
    set +u
    # shellcheck disable=SC1090
    source "$WAL_CACHE/colors.sh"
    set -u
elif [[ -f "$WAL_CACHE/colors" ]]; then
    mapfile -t wal_colors < "$WAL_CACHE/colors"
    background="${wal_colors[0]:-$background}"
    foreground="${wal_colors[7]:-$foreground}"
    color1="${wal_colors[1]:-$color1}"
    color3="${wal_colors[3]:-$color3}"
    color8="${wal_colors[8]:-$color8}"
    color10="${wal_colors[10]:-$color10}"
    color11="${wal_colors[11]:-$color11}"
    color12="${wal_colors[12]:-$color12}"
else
    fail "Pywal colors were not found in $WAL_CACHE"
fi

background="$(normalize_color "${background:-}" "#1a1b26")"
foreground="$(normalize_color "${foreground:-}" "#ffffff")"
color1="$(normalize_color "${color1:-}" "#f38ba8")"
color3="$(normalize_color "${color3:-}" "#f9e2af")"
color8="$(normalize_color "${color8:-}" "#6c7086")"
color10="$(normalize_color "${color10:-}" "#a6e3a1")"
color11="$(normalize_color "${color11:-}" "#8caaee")"
color12="$(normalize_color "${color12:-}" "#89b4fa")"

wallpaper_tmp="$(mktemp "$CACHE_DIR/.wallpaper.XXXXXX")"
config_tmp="$(mktemp "$CACHE_DIR/.theme-conf.XXXXXX")"
trap 'rm -f "$wallpaper_tmp" "$config_tmp"' EXIT

cp -- "$WALLPAPER" "$wallpaper_tmp"
chmod 0644 "$wallpaper_tmp"
mv -f -- "$wallpaper_tmp" "$CACHE_DIR/current_wallpaper"

cat > "$config_tmp" <<EOF_CONFIG
[General]
mode=pro
background=file://$CACHE_DIR/current_wallpaper
background_color=$background
foreground=$foreground
color1=$color1
color3=$color3
color8=$color8
color10=$color10
color11=$color11
color12=$color12
EOF_CONFIG

chmod 0644 "$config_tmp"
mv -f -- "$config_tmp" "$CACHE_DIR/theme.conf.user"
trap - EXIT

log "Dynamic Bubble synced with Pywal."
log "Accent: $color11"
log "Wallpaper: $WALLPAPER"
