[General]
# Modes: "standard" (fixed colors) or "pro" 
# (dynamic pywal colors and wallpaper)
# pro mode is needs sddm_sync.sh and it is auto apllied with the script)

mode="standard"

# --- USER CONFIGURATION ---
# Leave empty "" to automatically detect the system user.
# Enter a name in quotes to force a custom greeting (e.g., "Leonardo").
username=""

# --- STANDARD MODE SETTINGS ---
# These values are used if mode="standard" or as fallback
background="background.jpg"
color11="#8caaee"
background_color="#1a1b26"